name: CLI
on:
  release:
    types: [published]

jobs:
  cli-test:
    name: CLI tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/cli-')
    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  cli-build:
    needs: cli-test
    name: CLI build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            artifact_name: pigmnts
            asset_name: pigmnts-linux-18-04-amd64
          - os: ubuntu-16.04
            artifact_name: pigmnts
            asset_name: pigmnts-linux-16-04-amd64
          - os: macos-latest
            artifact_name: pigmnts
            asset_name: pigmnts-macos-amd64
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --locked
      - run: |
          strip target/release/${{ matrix.artifact_name }}
          mkdir ${{ matrix.asset_name }}
          cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}/
          cp README.md LICENSE.md ${{ matrix.asset_name }}/
          tar czvf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}