name: CLI
on:
  release:
    types: [published]

jobs:
  cli-test:
    name: CLI tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/cli-')
    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  cli-build-linux:
    needs: cli-test
    name: CLI build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
      - run: |
          mkdir linux
          cp target/release/pigmnts linux/
          cp README.md LICENSE.md linux/
          tar czvf linux.tar.gz linux
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cli-build-macos:
    needs: cli-test
    name: CLI build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v1
        with:
          name: macOS
          path: target/release/pigmnts
      - run: |
          mkdir macOS
          cp target/release/pigmnts macOS/
          cp README.md LICENSE.md macOS/
          tar czvf macOS.tar.gz macOS
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: macOS.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}