name: Lib
on:
  release:
    types: [published]

jobs:
  lib-test:
    name: Lib tests
    runs-on: ubuntu-latest
    env:
      wd: ./lib
    if: startsWith(github.ref, 'refs/tags/lib-')
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
        working-directory: ${{env.wd}}

  lib-publish-npm:
    needs: lib-test
    name: Lib publish npm
    runs-on: ubuntu-latest
    env:
      wd: ./lib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build -t web
        working-directory: ${{env.wd}}
      - run: wasm-pack publish
        working-directory: ${{env.wd}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  lib-publish-crate:
    needs: lib-test
    name: Lib publish crates.io
    runs-on: ubuntu-latest
    env:
      wd: ./lib
    steps:
      - uses: actions/checkout@v2
      - run: cargo login ${{ secrets.CRATES_TOKEN }}
      - run: cargo publish
        working-directory: ${{env.wd}}